apiVersion: batch/v1
kind: Job
metadata:
  name: headercheck-once
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: headercheck
          image: ghcr.io/aftabahmad019/headercheck:latest
          args: ["https://github.com"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false